### PR TITLE
Update reference for @goble_2019 - now published

### PR DESCRIPTION
**Pull request by stain**
.. as it is now early-access published on http://www.data-intelligence-journal.org/p/45/ aka https://doi.org/10.1162/dint_a_00033

It says year 2020 on the page.. not sure about that.. journals are weird.

### CODE REVIEW

**Comment by sneumann** [comment]
Hi, thanks for the update ! The build failure is due to a timeout in Travis. Yours, Steffen

**Comment by stanstrup** [comment]
@sneumann @jorainer I was unable to find a way to trigger travis again (I don't have the option that apparently should be there). Perhaps you have more access there and can trigger it to run again?

**Comment by sneumann** [comment]
I think we need to split into a base docker that has all the packages installed (which is what is taking so long) and then the book rendering on top. Yours, Steffen

**Comment by stanstrup** [comment]
Yeah. I guess that is easier with the new github workflow (and gitlab CI) than the current travis.

**Pull request merged**
